menu:
  title: "§8choose a server"
  size: 27

  freeze-player: true
  hide-players: true

  items:
    survival:
      material: DIAMOND_SWORD
      name: "§asurvival"
      slot: 11
      server: "survival"

    creative:
      material: GRASS_BLOCK
      name: "§bcreative"
      slot: 15
      server: "creative"
